services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: BUS_TRANSPORT
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql-ball:/var/lib/mysql
    ports:
      - 3306

  osrm-lk-data:
    image: pandorian7/sri-lanka-osrm-dataset:latest
    volumes:
      - osm-data-volume:/data

  osrm-lk:
    image: osrm/osrm-backend:latest
    volumes:
      - osm-data-volume:/data:ro
    depends_on:
      - osrm-lk-data
    ports:
      - 5000
    command: ["osrm-routed", "--algorithm", "mld", "/data/sri-lanka.osrm"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - BACKEND_INTERNAL_URL=http://backend:9090
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000

  backend:
    depends_on:
      - database
      - osrm-lk
    environment:
      - MYSQL_ROOT_PASSWORD
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/target
    ports:
      - 9090
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend

volumes:
  osm-data-volume:
  mysql-ball:
