CREATE TABLE IF NOT EXISTS routes (
    id SERIAL PRIMARY KEY,
    A_Name VARCHAR(255) NOT NULL,
    A_LAT DECIMAL(9,6) NOT NULL,
    A_LON DECIMAL(9,6) NOT NULL,
    B_Name VARCHAR(255) NOT NULL,
    B_LAT DECIMAL(9,6) NOT NULL,
    B_LON DECIMAL(9,6) NOT NULL
);

CREATE TABLE IF NOT EXISTS trips (
    id SERIAL PRIMARY KEY,
    Route_Id BIGINT UNSIGNED NOT NULL REFERENCES routes(id),
    Direction VARCHAR(10) CHECK (Direction IN ('forward','backward')),
    Loc_LAT DECIMAL(9,6) NOT NULL,
    Loc_LON DECIMAL(9,6) NOT NULL,
    Loc_Frac DECIMAL(5,4),
    Loc_TimeStamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id SERIAL PRIMARY KEY,
    Trip_Id BIGINT UNSIGNED NOT NULL REFERENCES trips(id),
    Loc_LAT DECIMAL(9,6) NOT NULL,
    Loc_LON DECIMAL(9,6) NOT NULL,
    Loc_Frac DECIMAL(5,4),
    Loc_TimeStamp TIMESTAMP NOT NULL
);
