CREATE TABLE IF NOT EXISTS routes (
    id SERIAL PRIMARY KEY,
    A_Name VARCHAR(255) NOT NULL,
    A_LAT DECIMAL(9,6) NOT NULL,
    A_LON DECIMAL(9,6) NOT NULL,
    B_Name VARCHAR(255) NOT NULL,
    B_LAT DECIMAL(9,6) NOT NULL,
    B_LON DECIMAL(9,6) NOT NULL,
    Polyline VARCHAR(1000) NOT NULL,
    Distance DECIMAL(12,3) NOT NULL,
    CONSTRAINT unique_route UNIQUE (A_Name, A_LAT, A_LON, B_Name, B_LAT, B_LON)
);

CREATE TABLE IF NOT EXISTS trips (
    id SERIAL PRIMARY KEY,
    Route_Id BIGINT UNSIGNED NOT NULL REFERENCES routes(id),
    Direction VARCHAR(10) CHECK (Direction IN ('forward','backward')),
    Loc_LAT DECIMAL(9,6) NOT NULL,
    Loc_LON DECIMAL(9,6) NOT NULL,
    Loc_Frac DECIMAL(5,4),
    Loc_TimeStamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id SERIAL PRIMARY KEY,
    Trip_Id BIGINT UNSIGNED NOT NULL REFERENCES trips(id),
    Loc_LAT DECIMAL(9,6) NOT NULL,
    Loc_LON DECIMAL(9,6) NOT NULL,
    Loc_Frac DECIMAL(5,4),
    Loc_TimeStamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS places (
    id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Loc_LAT DECIMAL(9,6) NOT NULL,
    Loc_LON DECIMAL(9,6) NOT NULL
);