name: Deploy FrontEnd to VPS

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'

jobs:
  frontend:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Build Docker image
          run: docker compose -f compose.production.yaml build frontend

        - name: Save Docker image as tarball
          run: docker save public-transport-tracker-frontend | gzip > frontend.tar.gz

        - name: Add VPS to known_hosts
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

        - name: Copy image to VPS
          env:
            HOST: ${{ secrets.VPS_HOST }}
            USER: ${{ secrets.VPS_USER }}
            KEY: ${{ secrets.VPS_SSH_KEY }}
          run: |
            echo "$KEY" > key.pem
            chmod 600 key.pem
            scp -i key.pem frontend.tar.gz $USER@$HOST:/tmp/

        - name: Load container on VPS
          env:
            HOST: ${{ secrets.VPS_HOST }}
            USER: ${{ secrets.VPS_USER }}
            KEY: ${{ secrets.VPS_SSH_KEY }}
          run: |
            ssh -i key.pem $USER@$HOST << 'EOF'
            docker load < /tmp/frontend.tar.gz
            EOF